version: "3.7"
services:
  zookeeper:
    image: zookeeper:3.5.5
    hostname: zookeeper
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 60s
    ports:
      - target: 2181
        published: 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    volumes:
      - zdata:/data
      - zlog:/datalog
    networks:
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 60s
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_REQUEST_TIMEOUT_MS: 600000
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094 # For localhost connection EXTERNAL://localhost:9094
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 16000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
volumes:
  zdata:
  zlog:
networks:
  kafka:
    driver: overlay
