version: "3.7"
services:
  mongo:
    image: mongo:4.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 60s
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
volumes:
  mongo: