version: "3.7"
services:
  mysql:
    image: mysql:8.0.18
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 60s
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test_db
      # MYSQL_USER: <<USERNAME>>
      # MYSQL_PASSWORD: <<PASSWORD>>
      # MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    networks:
      - host
networks:
  host:
volumes:
  mysql:
