version: "3.7"
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 1s
        max_attempts: 3
        window: 60s
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: redis
        target: /data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    command:
      - "redis-server"
      - "--requirepass parthi"
      - "--appendonly yes"
volumes:
  redis: