version: "3.7"
services:
 sonarqube:
  image: sonarqube:lts
  networks:
    - sonar
  ports:
    - target: 9000
      published: 9000
      protocol: tcp
      mode: host
  environment:
    sonar.jdbc.username: sonar
    sonar.jdbc.password: sonar
    sonar.jdbc.url: jdbc:postgresql://postgres:5432/sonar
  volumes:
      - type: volume
        source: sonarqube
        target: /opt/sonarqube
  deploy:
    mode: replicated
    replicas: 1

 postgres:
    image: postgres:latest
    networks:
      - sonar
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "udp://127.0.0.1:515"
#        tag: "postgres/{{.ImageName}}/{{.ID}}"
#        syslog-facility: local5
#        syslog-format: rfc5424micro
    deploy:
      mode: replicated
      replicas: 1
networks:
  sonar:
    name: sonar
    driver: overlay
    driver_opts:
      encrypted: "true"
volumes:
  sonarqube:
  postgresql: